using System.Collections.Generic;

namespace LocalDocAI.Persistence
{
    public static class LocalizationService
    {
        public static string CurrentLanguage { get; set; } = "vi";

        private static readonly Dictionary<string, Dictionary<string, string>> _translations = new Dictionary<string, Dictionary<string, string>>
        {
            ["vi"] = new()
            {
                ["tabLocalAI"] = "Local AI",
                ["grpMain"] = "Local Word AI",
                ["btnToggleSidebar"] = "AI Sidebar",
                ["btnToggleSidebar_tip"] = "Bật/tắt AI Sidebar",
                ["btnToggleSidebar_super"] = "Mở hoặc đóng bảng trợ lý AI bên phải.",
                ["btnQuickReview"] = "Review",
                ["btnQuickReview_tip"] = "Review vùng chọn hoặc tài liệu",
                ["btnRewrite"] = "Rewrite",
                ["btnRewrite_tip"] = "Viết lại vùng chọn",
                ["btnRedline"] = "Redline",
                ["btnRedline_tip"] = "Tạo redline với Track Changes",
                ["btnTranslate"] = "Dịch",
                ["btnTranslate_tip"] = "Dịch vùng chọn và chèn sau mỗi đoạn gốc",
                ["btnSettings"] = "Cài đặt",
                ["btnSettings_tip"] = "Cài đặt Local Word AI",
                ["grpCheck"] = "Kiểm tra",
                ["btnCheckComments"] = "Comments",
                ["btnCheckComments_tip"] = "Xử lý comments",
                ["btnCheckChanges"] = "Tracked Changes",
                ["btnCheckChanges_tip"] = "Phân tích tracked changes",
                ["btnCheckTerms"] = "Thuật ngữ",
                ["btnCheckTerms_tip"] = "Kiểm tra thuật ngữ nhất quán",
                ["btnFinalCheck"] = "Final Check",
                ["btnFinalCheck_tip"] = "Kiểm tra toàn diện trước phát hành",
                ["settingsTitle"] = "Cài đặt Local Word AI",
                ["lblLanguage"] = "Ngôn ngữ / Language:",
                ["lblBaseUrl"] = "LM Studio URL:",
                ["lblModel"] = "Model name:",
                ["lblTimeout"] = "Timeout (giây):",
                ["lblMaxTokens"] = "Max tokens:",
                ["lblTemperature"] = "Temperature:",
                ["chkTrackChanges"] = "Mặc định dùng Track Changes",
                ["chkConfirmBefore"] = "Xác nhận trước khi áp dụng",
                ["lblSkillsDir"] = "Thư mục Skills:",
                ["lblAuthor"] = "Tên tác giả AI:",
                ["btnTest"] = "Test kết nối",
                ["btnSave"] = "Lưu",
                ["btnCancel"] = "Hủy",
                ["lblModels"] = "Model:",
                ["lblStatus"] = "Đang kết nối...",
                ["lblStatusConnected"] = "● Đã kết nối",
                ["lblStatusDisconnected"] = "● Mất kết nối",
                ["lblNoModel"] = "LM Studio chưa chạy",
                ["connectionSuccess"] = "✓ Kết nối thành công",
                ["connectionFailed"] = "✗ Không kết nối được",
                ["urlInvalid"] = "URL không hợp lệ. Chỉ cho phép localhost hoặc 127.0.0.1.",
                ["urlInvalidShort"] = "URL không hợp lệ (chỉ cho phép localhost/127.0.0.1)",
                ["noText"] = "Không có văn bản để kiểm tra.",
                ["processing"] = "Đang xử lý...",
                ["error"] = "Lỗi",
                ["sidebarTitle"] = "Local Word AI",
                ["lblSelectContext"] = "Chọn nguồn:",
                ["lblChat"] = "Chat với AI:",
                ["lblSuggestions"] = "Gợi ý:",
                ["lblSkills"] = "Skills:",
                ["skillPlaceholder"] = "-- Chọn Skill --",
                ["btnReviewSelection"] = "Review vùng chọn",
                ["btnReviewDocument"] = "Review tài liệu",
                ["btnRewriteTab"] = "Viết lại",
                ["btnShorten"] = "Rút gọn",
                ["btnFormal"] = "Trang trọng",
                ["btnPassive"] = "Bị động → Chủ động",
                ["btnComments"] = "Comments",
                ["btnChanges"] = "Tracked Changes",
                ["btnFinalCheck"] = "Final Check",
                ["btnSend"] = "Gửi",
                ["btnStop"] = "Dừng",
                ["btnRunSkill"] = "Chạy Skill",
                ["btnClearChat"] = "Xóa chat",
                ["mnuTrackChange"] = "Track Change",
                ["mnuComment"] = "Comment",
                ["mnuHighlight"] = "Highlight",
                ["mnuSkip"] = "Bỏ qua",
            },
            ["en"] = new()
            {
                ["tabLocalAI"] = "Local AI",
                ["grpMain"] = "LocalDocAI",
                ["btnToggleSidebar"] = "AI Sidebar",
                ["btnToggleSidebar_tip"] = "Toggle AI Sidebar",
                ["btnToggleSidebar_super"] = "Open or close the AI assistant panel on the right.",
                ["btnQuickReview"] = "Review",
                ["btnQuickReview_tip"] = "Review selection or document",
                ["btnRewrite"] = "Rewrite",
                ["btnRewrite_tip"] = "Rewrite selected text",
                ["btnRedline"] = "Redline",
                ["btnRedline_tip"] = "Create redline with Track Changes",
                ["btnTranslate"] = "Translate",
                ["btnTranslate_tip"] = "Translate selection and insert after each original paragraph",
                ["btnSettings"] = "Settings",
                ["btnSettings_tip"] = "LocalDocAI Settings",
                ["grpCheck"] = "Checks",
                ["btnCheckComments"] = "Comments",
                ["btnCheckComments_tip"] = "Process comments",
                ["btnCheckChanges"] = "Tracked Changes",
                ["btnCheckChanges_tip"] = "Analyze tracked revisions",
                ["btnCheckTerms"] = "Terms",
                ["btnCheckTerms_tip"] = "Check terminology consistency",
                ["btnFinalCheck"] = "Final Check",
                ["btnFinalCheck_tip"] = "Comprehensive pre-release check",
                ["settingsTitle"] = "LocalDocAI Settings",
                ["lblLanguage"] = "Language / Ngôn ngữ:",
                ["lblBaseUrl"] = "LM Studio URL:",
                ["lblModel"] = "Model name:",
                ["lblTimeout"] = "Timeout (seconds):",
                ["lblMaxTokens"] = "Max tokens:",
                ["lblTemperature"] = "Temperature:",
                ["chkTrackChanges"] = "Use Track Changes by default",
                ["chkConfirmBefore"] = "Confirm before applying",
                ["lblSkillsDir"] = "Skills folder:",
                ["lblAuthor"] = "AI Author name:",
                ["btnTest"] = "Test connection",
                ["btnSave"] = "Save",
                ["btnCancel"] = "Cancel",
                ["lblModels"] = "Model:",
                ["lblStatus"] = "Connecting...",
                ["lblStatusConnected"] = "● Connected",
                ["lblStatusDisconnected"] = "● Disconnected",
                ["lblNoModel"] = "LM Studio not running",
                ["connectionSuccess"] = "✓ Connection successful",
                ["connectionFailed"] = "✗ Connection failed",
                ["urlInvalid"] = "Invalid URL. Only localhost or 127.0.0.1 allowed.",
                ["urlInvalidShort"] = "Invalid URL (only localhost/127.0.0.1 allowed)",
                ["noText"] = "No text to review.",
                ["processing"] = "Processing...",
                ["error"] = "Error",
                ["sidebarTitle"] = "Local Word AI",
                ["lblSelectContext"] = "Select source:",
                ["lblChat"] = "Chat with AI:",
                ["lblSuggestions"] = "Suggestions:",
                ["lblSkills"] = "Skills:",
                ["skillPlaceholder"] = "-- Select Skill --",
                ["btnReviewSelection"] = "Review selection",
                ["btnReviewDocument"] = "Review document",
                ["btnRewriteTab"] = "Rewrite",
                ["btnShorten"] = "Shorten",
                ["btnFormal"] = "Formal",
                ["btnPassive"] = "Passive → Active",
                ["btnComments"] = "Comments",
                ["btnChanges"] = "Tracked Changes",
                ["btnFinalCheck"] = "Final Check",
                ["btnSend"] = "Send",
                ["btnStop"] = "Stop",
                ["btnRunSkill"] = "Run Skill",
                ["btnClearChat"] = "Clear chat",
                ["mnuTrackChange"] = "Track Change",
                ["mnuComment"] = "Comment",
                ["mnuHighlight"] = "Highlight",
                ["mnuSkip"] = "Skip",
            },
            ["fr"] = new()
            {
                ["tabLocalAI"] = "Local AI",
                ["grpMain"] = "LocalDocAI",
                ["btnToggleSidebar"] = "AI Sidebar",
                ["btnToggleSidebar_tip"] = "Afficher/masquer le panneau latéral IA",
                ["btnToggleSidebar_super"] = "Ouvrir ou fermer le panneau assistant IA à droite.",
                ["btnQuickReview"] = "Review",
                ["btnQuickReview_tip"] = "Vérifier la sélection ou le document",
                ["btnRewrite"] = "Rewriter",
                ["btnRewrite_tip"] = "Réécrire le texte sélectionné",
                ["btnRedline"] = "Redline",
                ["btnRedline_tip"] = "Créer une redline avec le suivi des modifications",
                ["btnTranslate"] = "Traduire",
                ["btnTranslate_tip"] = "Traduire la sélection et insérer après chaque paragraphe original",
                ["btnSettings"] = "Paramètres",
                ["btnSettings_tip"] = "Paramètres de LocalDocAI",
                ["grpCheck"] = "Vérifications",
                ["btnCheckComments"] = "Commentaires",
                ["btnCheckComments_tip"] = "Traiter les commentaires",
                ["btnCheckChanges"] = "Suivi des modifs",
                ["btnCheckChanges_tip"] = "Analyser les révisions suivies",
                ["btnCheckTerms"] = "Termes",
                ["btnCheckTerms_tip"] = "Vérifier la cohérence terminologique",
                ["btnFinalCheck"] = "Vérif. finale",
                ["btnFinalCheck_tip"] = "Vérification complète avant publication",
                ["settingsTitle"] = "Paramètres LocalDocAI",
                ["lblLanguage"] = "Langue / Language:",
                ["lblBaseUrl"] = "URL LM Studio:",
                ["lblModel"] = "Nom du modèle:",
                ["lblTimeout"] = "Délai (secondes):",
                ["lblMaxTokens"] = "Jetons max:",
                ["lblTemperature"] = "Température:",
                ["chkTrackChanges"] = "Utiliser le suivi des modifications par défaut",
                ["chkConfirmBefore"] = "Confirmer avant d'appliquer",
                ["lblSkillsDir"] = "Dossier Skills:",
                ["lblAuthor"] = "Nom auteur IA:",
                ["btnTest"] = "Tester connexion",
                ["btnSave"] = "Enregistrer",
                ["btnCancel"] = "Annuler",
                ["lblModels"] = "Modèle:",
                ["lblStatus"] = "Connexion...",
                ["lblStatusConnected"] = "● Connecté",
                ["lblStatusDisconnected"] = "● Déconnecté",
                ["lblNoModel"] = "LM Studio ne fonctionne pas",
                ["connectionSuccess"] = "✓ Connexion réussie",
                ["connectionFailed"] = "✗ Connexion échouée",
                ["urlInvalid"] = "URL non valide. Seul localhost ou 127.0.0.1 est autorisé.",
                ["urlInvalidShort"] = "URL non valide (seul localhost/127.0.0.1 autorisé)",
                ["noText"] = "Aucun texte à vérifier.",
                ["processing"] = "Traitement en cours...",
                ["error"] = "Erreur",
                ["sidebarTitle"] = "Local Word AI",
                ["lblSelectContext"] = "Source :",
                ["lblChat"] = "Chat avec l'IA :",
                ["lblSuggestions"] = "Suggestions :",
                ["lblSkills"] = "Skills :",
                ["skillPlaceholder"] = "-- Sélectionner un Skill --",
                ["btnReviewSelection"] = "Vérifier sélection",
                ["btnReviewDocument"] = "Vérifier document",
                ["btnRewriteTab"] = "Réécrire",
                ["btnShorten"] = "Raccourcir",
                ["btnFormal"] = "Formel",
                ["btnPassive"] = "Passif → Actif",
                ["btnComments"] = "Commentaires",
                ["btnChanges"] = "Suivi modifs",
                ["btnFinalCheck"] = "Vérif. finale",
                ["btnSend"] = "Envoyer",
                ["btnStop"] = "Arrêter",
                ["btnRunSkill"] = "Exécuter Skill",
                ["btnClearChat"] = "Effacer chat",
                ["mnuTrackChange"] = "Suivi modif",
                ["mnuComment"] = "Commentaire",
                ["mnuHighlight"] = "Surligner",
                ["mnuSkip"] = "Ignorer",
            }
        };

        private static readonly Dictionary<string, string> _languageNames = new Dictionary<string, string>
        {
            ["vi"] = "Tiếng Việt",
            ["en"] = "English",
            ["fr"] = "Français"
        };

        public static string Get(string key)
        {
            if (_translations.TryGetValue(CurrentLanguage, out var dict))
            {
                if (dict.TryGetValue(key, out var value))
                    return value;
            }
            if (_translations.TryGetValue("en", out var enDict) && enDict.TryGetValue(key, out var enValue))
                return enValue;
            return key;
        }

        public static string GetLanguageName(string code)
        {
            return _languageNames.TryGetValue(code, out var name) ? name : code;
        }

        public static List<string> GetAvailableLanguages()
        {
            return new List<string> { "vi", "en", "fr" };
        }

        public static void SetLanguage(string code)
        {
            if (GetAvailableLanguages().Contains(code))
                CurrentLanguage = code;
        }
    }
}
