using System.Collections.Generic;

namespace LocalDocAI.Persistence
{
    public static class LocalizationService
    {
        public static string CurrentLanguage { get; set; } = "vi";

        private static readonly Dictionary<string, Dictionary<string, string>> _translations = new Dictionary<string, Dictionary<string, string>>
        {
            ["vi"] = new()
            {
                ["tabLocalAI"] = "Local AI",
                ["grpMain"] = "Local Word AI",
                ["btnToggleSidebar"] = "AI Sidebar",
                ["btnToggleSidebar_tip"] = "Bật/tắt AI Sidebar",
                ["btnToggleSidebar_super"] = "Mở hoặc đóng bảng trợ lý AI bên phải.",
                ["btnQuickReview"] = "Review",
                ["btnQuickReview_tip"] = "Review vùng chọn hoặc tài liệu",
                ["btnRewrite"] = "Rewrite",
                ["btnRewrite_tip"] = "Viết lại vùng chọn",
                ["btnRedline"] = "Redline",
                ["btnRedline_tip"] = "Tạo redline với Track Changes",
                ["btnTranslate"] = "Dịch",
                ["btnTranslate_tip"] = "Dịch vùng chọn và chèn sau mỗi đoạn gốc",
                ["btnSettings"] = "Cài đặt",
                ["btnSettings_tip"] = "Cài đặt Local Word AI",
                ["grpCheck"] = "Kiểm tra",
                ["btnCheckComments"] = "Comments",
                ["btnCheckComments_tip"] = "Xử lý comments",
                ["btnCheckChanges"] = "Tracked Changes",
                ["btnCheckChanges_tip"] = "Phân tích tracked changes",
                ["btnCheckTerms"] = "Thuật ngữ",
                ["btnCheckTerms_tip"] = "Kiểm tra thuật ngữ nhất quán",
                ["btnFinalCheck"] = "Final Check",
                ["btnFinalCheck_tip"] = "Kiểm tra toàn diện trước phát hành",
                ["settingsTitle"] = "Cài đặt Local Word AI",
                ["lblLanguage"] = "Ngôn ngữ / Language:",
                ["lblBaseUrl"] = "LM Studio URL:",
                ["lblModel"] = "Model name:",
                ["lblTimeout"] = "Timeout (giây):",
                ["lblMaxTokens"] = "Max tokens:",
                ["lblTemperature"] = "Temperature:",
                ["chkTrackChanges"] = "Mặc định dùng Track Changes",
                ["chkConfirmBefore"] = "Xác nhận trước khi áp dụng",
                ["lblSkillsDir"] = "Thư mục Skills:",
                ["lblAuthor"] = "Tên tác giả AI:",
                ["btnTest"] = "Test kết nối",
                ["btnSave"] = "Lưu",
                ["btnCancel"] = "Hủy",
                ["lblModels"] = "Model:",
                ["lblStatus"] = "Đang kết nối...",
                ["lblStatusConnected"] = "● Đã kết nối",
                ["lblStatusDisconnected"] = "● Mất kết nối",
                ["lblNoModel"] = "LM Studio chưa chạy",
                ["connectionSuccess"] = "✓ Kết nối thành công",
                ["connectionFailed"] = "✗ Không kết nối được",
                ["urlInvalid"] = "URL không hợp lệ. Chỉ cho phép localhost hoặc 127.0.0.1.",
                ["urlInvalidShort"] = "URL không hợp lệ (chỉ cho phép localhost/127.0.0.1)",
                ["noText"] = "Không có văn bản để kiểm tra.",
                ["processing"] = "Đang xử lý...",
                ["error"] = "Lỗi",
                ["sidebarTitle"] = "Local Word AI",
                ["lblSelectContext"] = "Chọn nguồn:",
                ["lblChat"] = "Chat với AI:",
                ["lblSuggestions"] = "Gợi ý:",
                ["lblSkills"] = "Skills:",
                ["skillPlaceholder"] = "-- Chọn Skill --",
                ["btnReviewSelection"] = "Review vùng chọn",
                ["btnReviewDocument"] = "Review tài liệu",
                ["btnRewriteTab"] = "Viết lại",
                ["btnShorten"] = "Rút gọn",
                ["btnFormal"] = "Trang trọng",
                ["btnPassive"] = "Bị động → Chủ động",
                ["lblOriginal"] = "Bản gốc",
                ["lblRewritten"] = "Viết lại",
                ["btnComments"] = "Comments",
                ["btnChanges"] = "Tracked Changes",
                ["btnFinalCheck"] = "Final Check",
                ["btnSend"] = "Gửi",
                ["btnStop"] = "Dừng",
                ["btnRunSkill"] = "Chạy Skill",
                ["btnClearChat"] = "Xóa chat",
                ["mnuTrackChange"] = "Track Change",
                ["mnuComment"] = "Comment",
                ["mnuHighlight"] = "Highlight",
                ["mnuSkip"] = "Bỏ qua",
                ["mnuApplyAll"] = "Áp dụng tất cả an toàn",
                ["actionSuccess"] = "✓ Đã thực hiện {0} thao tác thành công.",
                ["actionFailed"] = "✗ {0} thao tác thất bại.",
                ["lblProgress"] = "Đang xử lý...",
                ["rewritePrompt"] = "Yêu cầu viết lại (vd: 'trang trọng hơn', 'ngắn gọn hơn'):",
                ["rewriteTitle"] = "Viết lại",
                ["noText"] = "Không có văn bản.",
                ["textNoDocOpen"] = "Không có tài liệu đang mở.",
                ["noComments"] = "Tài liệu không có comment.",
                ["analyzing"] = "Đang phân tích {0} comments...",
                ["noTrackedChanges"] = "Tài liệu không có tracked changes.",
                ["analyzingChanges"] = "Đang phân tích {0} tracked changes...",
                ["noTextSelect"] = "Không có văn bản.",
                ["checkingPassive"] = "Đang kiểm tra câu bị động...",
                ["foundIssues"] = "Tìm thấy {0} câu bị động/mơ hồ.",
                ["checkingTerms"] = "Đang kiểm tra thuật ngữ...",
                ["foundTermIssues"] = "Tìm thấy {0} vấn đề thuật ngữ.",
                ["checkingFinal"] = "Đang kiểm tra toàn diện...",
                ["finalDone"] = "Final check hoàn tất. Tổng cộng {0} vấn đề.",
                ["replying"] = "Đang trả lời...",
                ["performingActions"] = "Đang thực hiện {0} thao tác...",
                ["stopped"] = "Đã dừng.",
                ["runningSkill"] = "Đang chạy skill: {0}...",
                ["skillDone"] = "Skill '{0}' hoàn tất. {1}",
                ["skillError"] = "Skill lỗi: {0}",
                ["translateTargetLang"] = "Nhập ngôn ngữ đích (vd: tiếng Anh, tiếng Pháp, tiếng Trung...):",
                ["translateTitle"] = "Dịch văn bản",
                ["defaultLang"] = "tiếng Anh",
                ["translatingTo"] = "Đang dịch sang {0}...",
                ["noDocOpen"] = "Không có tài liệu đang mở.",
                ["noTextSelectTranslate"] = "Vui lòng chọn văn bản cần dịch.",
                ["noParagraphFound"] = "Không tìm thấy đoạn văn trong vùng chọn.",
                ["insertingTranslations"] = "Đang chèn {0} đoạn dịch...",
                ["translationDone"] = "✓ Đã dịch và chèn {0} đoạn văn sau mỗi đoạn gốc (tiếng {1})",
                ["cancelledTranslate"] = "Đã hủy dịch.",
                ["reviewingSelection"] = "Đang kiểm tra...",
                ["reviewPrompt"] = "Kiểm tra: {0}",
                ["foundIssuesReview"] = "Tìm thấy {0} vấn đề.",
                ["reviewingDoc"] = "Đang kiểm tra tài liệu...",
                ["reviewingPart"] = "Đang kiểm tra phần {0}/{1}...",
                ["reviewDone"] = "Kiểm tra xong. Tìm thấy {0} vấn đề.",
                ["rewriting"] = "Đang viết lại...",
                ["chooseText"] = "Hãy chọn đoạn văn bản cần viết lại.",
            },
            ["en"] = new()
            {
                ["tabLocalAI"] = "Local AI",
                ["grpMain"] = "LocalDocAI",
                ["btnToggleSidebar"] = "AI Sidebar",
                ["btnToggleSidebar_tip"] = "Toggle AI Sidebar",
                ["btnToggleSidebar_super"] = "Open or close the AI assistant panel on the right.",
                ["btnQuickReview"] = "Review",
                ["btnQuickReview_tip"] = "Review selection or document",
                ["btnRewrite"] = "Rewrite",
                ["btnRewrite_tip"] = "Rewrite selected text",
                ["btnRedline"] = "Redline",
                ["btnRedline_tip"] = "Create redline with Track Changes",
                ["btnTranslate"] = "Translate",
                ["btnTranslate_tip"] = "Translate selection and insert after each original paragraph",
                ["btnSettings"] = "Settings",
                ["btnSettings_tip"] = "LocalDocAI Settings",
                ["grpCheck"] = "Checks",
                ["btnCheckComments"] = "Comments",
                ["btnCheckComments_tip"] = "Process comments",
                ["btnCheckChanges"] = "Tracked Changes",
                ["btnCheckChanges_tip"] = "Analyze tracked revisions",
                ["btnCheckTerms"] = "Terms",
                ["btnCheckTerms_tip"] = "Check terminology consistency",
                ["btnFinalCheck"] = "Final Check",
                ["btnFinalCheck_tip"] = "Comprehensive pre-release check",
                ["settingsTitle"] = "LocalDocAI Settings",
                ["lblLanguage"] = "Language / Ngôn ngữ:",
                ["lblBaseUrl"] = "LM Studio URL:",
                ["lblModel"] = "Model name:",
                ["lblTimeout"] = "Timeout (seconds):",
                ["lblMaxTokens"] = "Max tokens:",
                ["lblTemperature"] = "Temperature:",
                ["chkTrackChanges"] = "Use Track Changes by default",
                ["chkConfirmBefore"] = "Confirm before applying",
                ["lblSkillsDir"] = "Skills folder:",
                ["lblAuthor"] = "AI Author name:",
                ["btnTest"] = "Test connection",
                ["btnSave"] = "Save",
                ["btnCancel"] = "Cancel",
                ["lblModels"] = "Model:",
                ["lblStatus"] = "Connecting...",
                ["lblStatusConnected"] = "● Connected",
                ["lblStatusDisconnected"] = "● Disconnected",
                ["lblNoModel"] = "LM Studio not running",
                ["connectionSuccess"] = "✓ Connection successful",
                ["connectionFailed"] = "✗ Connection failed",
                ["urlInvalid"] = "Invalid URL. Only localhost or 127.0.0.1 allowed.",
                ["urlInvalidShort"] = "Invalid URL (only localhost/127.0.0.1 allowed)",
                ["noText"] = "No text to review.",
                ["processing"] = "Processing...",
                ["error"] = "Error",
                ["sidebarTitle"] = "Local Word AI",
                ["lblSelectContext"] = "Select source:",
                ["lblChat"] = "Chat with AI:",
                ["lblSuggestions"] = "Suggestions:",
                ["lblSkills"] = "Skills:",
                ["skillPlaceholder"] = "-- Select Skill --",
                ["btnReviewSelection"] = "Review selection",
                ["btnReviewDocument"] = "Review document",
                ["btnRewriteTab"] = "Rewrite",
                ["btnShorten"] = "Shorten",
                ["btnFormal"] = "Formal",
                ["btnPassive"] = "Passive → Active",
                ["lblOriginal"] = "Original",
                ["lblRewritten"] = "Rewritten",
                ["btnComments"] = "Comments",
                ["btnChanges"] = "Tracked Changes",
                ["btnFinalCheck"] = "Final Check",
                ["btnSend"] = "Send",
                ["btnStop"] = "Stop",
                ["btnRunSkill"] = "Run Skill",
                ["btnClearChat"] = "Clear chat",
                ["mnuTrackChange"] = "Track Change",
                ["mnuComment"] = "Comment",
                ["mnuHighlight"] = "Highlight",
                ["mnuSkip"] = "Skip",
                ["mnuApplyAll"] = "Apply all safe",
                ["actionSuccess"] = "✓ Successfully applied {0} actions.",
                ["actionFailed"] = "✗ {0} actions failed.",
                ["lblProgress"] = "Processing...",
                ["rewritePrompt"] = "Rewrite instruction (e.g. 'more formal', 'shorter'):",
                ["rewriteTitle"] = "Rewrite",
                ["noText"] = "No text.",
                ["textNoDocOpen"] = "No document is open.",
                ["noComments"] = "Document has no comments.",
                ["analyzing"] = "Analyzing {0} comments...",
                ["noTrackedChanges"] = "Document has no tracked changes.",
                ["analyzingChanges"] = "Analyzing {0} tracked changes...",
                ["noTextSelect"] = "No text.",
                ["checkingPassive"] = "Checking passive voice...",
                ["foundIssues"] = "Found {0} passive/vague sentences.",
                ["checkingTerms"] = "Checking terminology...",
                ["foundTermIssues"] = "Found {0} terminology issues.",
                ["checkingFinal"] = "Running final check...",
                ["finalDone"] = "Final check complete. Total {0} issues found.",
                ["replying"] = "Replying...",
                ["performingActions"] = "Performing {0} actions...",
                ["stopped"] = "Stopped.",
                ["runningSkill"] = "Running skill: {0}...",
                ["skillDone"] = "Skill '{0}' completed. {1}",
                ["skillError"] = "Skill error: {0}",
                ["translateTargetLang"] = "Target language (e.g. English, French, Chinese...):",
                ["translateTitle"] = "Translate text",
                ["defaultLang"] = "English",
                ["translatingTo"] = "Translating to {0}...",
                ["noDocOpen"] = "No document is open.",
                ["noTextSelectTranslate"] = "Please select text to translate.",
                ["noParagraphFound"] = "No paragraph found in selection.",
                ["insertingTranslations"] = "Inserting {0} translated paragraphs...",
                ["translationDone"] = "✓ Translated and inserted {0} paragraphs after each original (in {1})",
                ["cancelledTranslate"] = "Translation cancelled.",
                ["reviewingSelection"] = "Reviewing...",
                ["reviewPrompt"] = "Review: {0}",
                ["foundIssuesReview"] = "Found {0} issues.",
                ["reviewingDoc"] = "Reviewing document...",
                ["reviewingPart"] = "Reviewing part {0}/{1}...",
                ["reviewDone"] = "Review complete. Found {0} issues.",
                ["rewriting"] = "Rewriting...",
                ["chooseText"] = "Select text to rewrite.",
            },
            ["fr"] = new()
            {
                ["tabLocalAI"] = "Local AI",
                ["grpMain"] = "LocalDocAI",
                ["btnToggleSidebar"] = "AI Sidebar",
                ["btnToggleSidebar_tip"] = "Afficher/masquer le panneau latéral IA",
                ["btnToggleSidebar_super"] = "Ouvrir ou fermer le panneau assistant IA à droite.",
                ["btnQuickReview"] = "Review",
                ["btnQuickReview_tip"] = "Vérifier la sélection ou le document",
                ["btnRewrite"] = "Rewriter",
                ["btnRewrite_tip"] = "Réécrire le texte sélectionné",
                ["btnRedline"] = "Redline",
                ["btnRedline_tip"] = "Créer une redline avec le suivi des modifications",
                ["btnTranslate"] = "Traduire",
                ["btnTranslate_tip"] = "Traduire la sélection et insérer après chaque paragraphe original",
                ["btnSettings"] = "Paramètres",
                ["btnSettings_tip"] = "Paramètres de LocalDocAI",
                ["grpCheck"] = "Vérifications",
                ["btnCheckComments"] = "Commentaires",
                ["btnCheckComments_tip"] = "Traiter les commentaires",
                ["btnCheckChanges"] = "Suivi des modifs",
                ["btnCheckChanges_tip"] = "Analyser les révisions suivies",
                ["btnCheckTerms"] = "Termes",
                ["btnCheckTerms_tip"] = "Vérifier la cohérence terminologique",
                ["btnFinalCheck"] = "Vérif. finale",
                ["btnFinalCheck_tip"] = "Vérification complète avant publication",
                ["settingsTitle"] = "Paramètres LocalDocAI",
                ["lblLanguage"] = "Langue / Language:",
                ["lblBaseUrl"] = "URL LM Studio:",
                ["lblModel"] = "Nom du modèle:",
                ["lblTimeout"] = "Délai (secondes):",
                ["lblMaxTokens"] = "Jetons max:",
                ["lblTemperature"] = "Température:",
                ["chkTrackChanges"] = "Utiliser le suivi des modifications par défaut",
                ["chkConfirmBefore"] = "Confirmer avant d'appliquer",
                ["lblSkillsDir"] = "Dossier Skills:",
                ["lblAuthor"] = "Nom auteur IA:",
                ["btnTest"] = "Tester connexion",
                ["btnSave"] = "Enregistrer",
                ["btnCancel"] = "Annuler",
                ["lblModels"] = "Modèle:",
                ["lblStatus"] = "Connexion...",
                ["lblStatusConnected"] = "● Connecté",
                ["lblStatusDisconnected"] = "● Déconnecté",
                ["lblNoModel"] = "LM Studio ne fonctionne pas",
                ["connectionSuccess"] = "✓ Connexion réussie",
                ["connectionFailed"] = "✗ Connexion échouée",
                ["urlInvalid"] = "URL non valide. Seul localhost ou 127.0.0.1 est autorisé.",
                ["urlInvalidShort"] = "URL non valide (seul localhost/127.0.0.1 autorisé)",
                ["noText"] = "Aucun texte à vérifier.",
                ["processing"] = "Traitement en cours...",
                ["error"] = "Erreur",
                ["sidebarTitle"] = "Local Word AI",
                ["lblSelectContext"] = "Source :",
                ["lblChat"] = "Chat avec l'IA :",
                ["lblSuggestions"] = "Suggestions :",
                ["lblSkills"] = "Skills :",
                ["skillPlaceholder"] = "-- Sélectionner un Skill --",
                ["btnReviewSelection"] = "Vérifier sélection",
                ["btnReviewDocument"] = "Vérifier document",
                ["btnRewriteTab"] = "Réécrire",
                ["btnShorten"] = "Raccourcir",
                ["btnFormal"] = "Formel",
                ["btnPassive"] = "Passif → Actif",
                ["lblOriginal"] = "Original",
                ["lblRewritten"] = "Réécrit",
                ["btnComments"] = "Commentaires",
                ["btnChanges"] = "Suivi modifs",
                ["btnFinalCheck"] = "Vérif. finale",
                ["btnSend"] = "Envoyer",
                ["btnStop"] = "Arrêter",
                ["btnRunSkill"] = "Exécuter Skill",
                ["btnClearChat"] = "Effacer chat",
                ["mnuTrackChange"] = "Suivi modif",
                ["mnuComment"] = "Commentaire",
                ["mnuHighlight"] = "Surligner",
                ["mnuSkip"] = "Ignorer",
                ["mnuApplyAll"] = "Appliquer tous (sûrs)",
                ["actionSuccess"] = "✓ {0} action(s) appliquée(s) avec succès.",
                ["actionFailed"] = "✗ {0} action(s) échouée(s).",
                ["lblProgress"] = "Traitement en cours...",
                ["rewritePrompt"] = "Instruction de réécriture (ex: 'plus formel', 'plus court') :",
                ["rewriteTitle"] = "Réécrire",
                ["noText"] = "Aucun texte.",
                ["textNoDocOpen"] = "Aucun document ouvert.",
                ["noComments"] = "Le document n'a pas de commentaires.",
                ["analyzing"] = "Analyse de {0} commentaires...",
                ["noTrackedChanges"] = "Le document n'a pas de modifications suivies.",
                ["analyzingChanges"] = "Analyse de {0} modifications suivies...",
                ["noTextSelect"] = "Aucun texte.",
                ["checkingPassive"] = "Vérification des voix passives...",
                ["foundIssues"] = "{0} phrases passives/floues trouvées.",
                ["checkingTerms"] = "Vérification terminologique...",
                ["foundTermIssues"] = "{0} problèmes terminologiques trouvés.",
                ["checkingFinal"] = "Vérification finale en cours...",
                ["finalDone"] = "Vérification finale terminée. Total {0} problèmes.",
                ["replying"] = "Réponse en cours...",
                ["performingActions"] = "Exécution de {0} actions...",
                ["stopped"] = "Arrêté.",
                ["runningSkill"] = "Exécution du skill : {0}...",
                ["skillDone"] = "Skill '{0}' terminé. {1}",
                ["skillError"] = "Erreur de skill : {0}",
                ["translateTargetLang"] = "Langue cible (ex: anglais, français, chinois...) :",
                ["translateTitle"] = "Traduire le texte",
                ["defaultLang"] = "anglais",
                ["translatingTo"] = "Traduction vers {0}...",
                ["noDocOpen"] = "Aucun document ouvert.",
                ["noTextSelectTranslate"] = "Veuillez sélectionner le texte à traduire.",
                ["noParagraphFound"] = "Aucun paragraphe trouvé dans la sélection.",
                ["insertingTranslations"] = "Insertion de {0} paragraphes traduits...",
                ["translationDone"] = "✓ Traduit et inséré {0} paragraphes après chaque original (en {1})",
                ["cancelledTranslate"] = "Traduction annulée.",
                ["reviewingSelection"] = "Vérification en cours...",
                ["reviewPrompt"] = "Vérification : {0}",
                ["foundIssuesReview"] = "{0} problèmes trouvés.",
                ["reviewingDoc"] = "Vérification du document...",
                ["reviewingPart"] = "Vérification partie {0}/{1}...",
                ["reviewDone"] = "Vérification terminée. {0} problèmes trouvés.",
                ["rewriting"] = "Réécriture en cours...",
                ["chooseText"] = "Sélectionnez le texte à réécrire.",
            }
        };

        private static readonly Dictionary<string, string> _languageNames = new Dictionary<string, string>
        {
            ["vi"] = "Tiếng Việt",
            ["en"] = "English",
            ["fr"] = "Français"
        };

        public static string Get(string key)
        {
            if (_translations.TryGetValue(CurrentLanguage, out var dict))
            {
                if (dict.TryGetValue(key, out var value))
                    return value;
            }
            if (_translations.TryGetValue("en", out var enDict) && enDict.TryGetValue(key, out var enValue))
                return enValue;
            return key;
        }

        public static string GetLanguageName(string code)
        {
            return _languageNames.TryGetValue(code, out var name) ? name : code;
        }

        public static List<string> GetAvailableLanguages()
        {
            return new List<string> { "vi", "en", "fr" };
        }

        public static void SetLanguage(string code)
        {
            if (GetAvailableLanguages().Contains(code))
                CurrentLanguage = code;
        }
    }
}
